---
title: "git_01"
author: "Clinton Boone"
date: "Fall semester"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits to different branches
Our project will be done using a sequence of save and commits and branch actions.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
“You are old, Father William,” the young man said,  
“And your hair has become very white;  
And yet you incessantly stand on your head –  
Do you think, at your age, it is right?”  
  
“In my youth,” Father William replied to his son,  
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->

## Second Verse  
The buzz-saw snarled and rattled in the yard  
And made dust and dropped stove-length sticks of wood,  
Sweet-scented stuff when the breeze drew across it.  
And from there those that lifted eyes could count  
Five mountain ranges one behind the other   
<!--Put the first five lines of a poem by Robert Frost here!-->

## Third Verse
The sun was shining on the sea,  
Shining with all his might:  
He did his very best to make  
The billows smooth and bright--  
And this was odd, because it was  
The middle of the night.  
  
The moon was shining sulkily,  
Because she thought the sun  
Had got no business to be there  
After the day was done--  
"It's very rude of him," she said,  
"To come and spoil the fun!"  
<!--Put the first two verses of The Walrus and the Carpenter here!-->

## Last Verse  
Once upon a midnight dreary, while I pondered, weak and weary,  
Over many a quaint and curious volume of forgotten lore—  
    While I nodded, nearly napping, suddenly there came a tapping,  
As of some one gently rapping, rapping at my chamber door.  
“’Tis some visitor,” I muttered, “tapping at my chamber door—  
            Only this and nothing more.”  

  Ah, distinctly I remember it was in the bleak December;  
And each separate dying ember wrought its ghost upon the floor.  
<!--Put a short poem of your choice 8-20 lines,here!-->
